stages:
- deploy

deploy_staging:
stage: deploy
script:
- cd /var/www/htdocs/new-staging
- git pull
only:
- develop
tags:
- staging

deploy_production:
stage: deploy
script:
- cd /var/www/htdocs/new
- git pull
only:
- master
tags:
- production
