stages:
- deploy

deploy_staging:
stage: deploy
script:
- cd /var/www/htdocs/wp-content/themes/your-theme
- git pull
only:
- develop
tags:
- staging

deploy_production:
stage: deploy
script:
- cd /var/www/htdocs/wp-content/themes/your-theme
- git pull
only:
- master
tags:
- production
